plugins {
    id 'java'
    id 'org.jetbrains.kotlin.jvm'
}

// Groovy
repositories {
    mavenCentral()
    maven {
        url = uri("https://maven.pkg.github.com/Ingenieria-de-Sistemas-123/PrintScript")
        credentials {
            username = findProperty("gpr.user")
                    ?: System.getenv("GPR_USER")
                    ?: System.getenv("GITHUB_ACTOR")
            password = findProperty("gpr.key")
                    ?: System.getenv("GPR_KEY")
                    ?: System.getenv("GITHUB_TOKEN")
        }
    }
}


java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

test {
    minHeapSize = "5m" // initial heap size
    maxHeapSize = "7m" // maximum heap size
}

dependencies {
    testImplementation 'junit:junit:4.13.1'
    implementation 'org.printscript:common:1.2'
    implementation 'org.printscript:formatter:3.2'
    implementation 'org.printscript:interpreter:2.1'
    implementation 'org.printscript:lexer:1.6'
    implementation 'org.printscript:linter:1.6'
    implementation 'org.printscript:parser:1.5'
    implementation 'org.printscript:token:1.2'
    implementation 'org.printscript:runner:1.6'
}

test {
    environment "BEST_FOOTBALL_CLUB", "San Lorenzo" //River es mejor
    useJUnit()
}
